### PR TITLE
Simple Meteobridge parser

### PR DESCRIPTION
**Pull request by ve7gel**
This is a simple parser created to pull data from a Meteobridge weather interface directly into the Rainmachine.  Please review and comment. (First time submitting a Python program for me!)

I've compared the charts with the data posted by the pws-parser in parallel and it seems to be working as expected.

### CODE REVIEW

**Comment by nicupavel** [comment]
Thanks for the contribution. As far as I can see is this a weather parser that fetches data from WUnderground/Weather.com ?

**Comment by nicupavel** [comment]
Oh I also see a meteobridge parser, could you resend the pull request that doesn't delete the other parsers ?

**Comment by ve7gel** [comment]
Re-issued the pull request.
You can ignore the weather.com one.  I started on that before you posted the new 2019 Wunderground-beta, which serves the same purpose, only better.  Let me know if you see anything in the data not being handled as expected.

**Comment by nicupavel** [comment]
Pull request merged manually.

**Pull request closed without merging**
